### ISSUE TITLE
Submit to Flathub

### ISSUE THREAD

**Issue by leaf-node** [okcode-studio/open_alert_viewer#180]
* [x] Update metadata in this repo
* [x] Tag a new release
* [x] Using binaries compiled by GitHub Actions
    * [x] [Submit the metadata upstream](https://docs.flathub.org/docs/for-app-authors/submission/)
* [ ] [Build from source](https://discourse.flathub.org/t/to-all-publishers-of-flutter-apps-lets-build-from-source/8682)

**Comment by leaf-node** [comment]
This is what I have so far. (I'll keep this updated until the metadata is submitted upstream).

The `local` source and commands using the `local` directory will need to be removed from the manifest, and paths rewritten, once the relevant files are in the main repo.

```yaml
id: studio.okcode.open_alert_viewer
runtime: org.freedesktop.Platform
runtime-version: "24.08"
sdk: org.freedesktop.Sdk
command: open_alert_viewer
finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --device=dri
  - --socket=pulseaudio
  - --talk-name=org.freedesktop.Notifications
modules:
  - name: open_alert_viewer
    buildsystem: simple
    build-commands:
      - cp -R bundle/* /app/
      - mkdir /app/bin/
      - ln -s ../open_alert_viewer /app/bin/open_alert_viewer
      - install -Dm644 local/assets/icon/open_alert_viewer_circle_full.svg /app/share/icons/hicolor/scalable/apps/studio.okcode.open_alert_viewer.svg
      - install -Dm644 local/linux/studio.okcode.open_alert_viewer.desktop /app/share/applications/studio.okcode.open_alert_viewer.desktop
      - install -Dm644 local/linux/studio.okcode.open_alert_viewer.metainfo.xml /app/share/metainfo/studio.okcode.open_alert_viewer.metainfo.xml
    sources:
      - type: dir
        path: local
        dest: local
      - type: archive
        url: https://github.com/okcode-studio/open_alert_viewer/archive/refs/tags/v1.1.8.tar.gz
        sha256: e7f4421a48a9f5a33c64912349bd9d7442a0c16fb1d7f5b6ba11502f51ebcab9
        dest: sources
      - type: archive
        only-arches:
          - x86_64
        url: https://github.com/okcode-studio/open_alert_viewer/releases/download/v1.1.8/oav-bundle-linux-x86_64.tar.gz
        sha256: 470c98b2921ceb92d1e6971f0720e0f910c8bfa33f5e0e04dc51e4fcabd2bb94
        dest: bundle
```
